index.md
This is instead of the blank pages they currently point to.
=> Updated links to Shapeless and Spire GitHub repositories

_posts/2015-02-26-rawtypes.md
=> New post: "Existential types are not raw types"

_posts/2015-07-13-type-members-parameters.md
First in a series on type parameters and members, for posting on July 13.
=> New post: "Type members are [almost] type parameters"

_posts/2015-07-19-forget-refinement-aux.md, _posts/2015-07-23-type-projection.md
Fourth in a series on type parameters and members, for posting on July 23.  Preceded by #45.
NB: Links to the previous post will not work on GH, because they use `post_url`, which only works on the site.
=> New post: "Type projection isn't that specific"

_posts/2015-07-27-nested-existentials.md, _posts/2015-07-30-values-never-change-types.md
Sixth in a series on type parameters and members, for posting on July 30. Preceded by #47.
NB: Links to the previous post will not work on GH, because they use `post_url`, which only works on the site.
=> New post: "Values never change types"

conduct.md
This is a first pass at a resolution for #32. There is almost certainly
room for improvement and expansion. I wanted to get _something_ out
there, as this has been delayed for far too long.
@kpfell if you are still interested in this matter, I would greatly appreciate a review from you!
=> Clarify "community venues" in CoC

conduct.md
This is a first pass at a resolution to #33.
I've added email links for a few people that already had their email
addresses publicly available and that I felt confident would be happy to
be on this contact list. We can definitely add more contacts if there
are others who would be willing to be contacts.
=> Clarify "community staff" in CoC

index.md
I found it surprisingly hard to find the CfP, so thought maybe others would too.  This PR adds the CfP on the home page:
Just an idea. It's ok --  I'm not precious about it. Feel free to close or re-work if it's not really what's wanted :-)
=> Add CfP to homepage

_events/2016-09-30-conf-cadiz.md
- Added complete description of the conference
- Added empty talks proposals list (the idea is having it updated with the new proposals and sharing it by Twitter)
- Added a button for C4P, please @larsrh , can you review it? I don't know if this is the better way to do it. This is the platform that we use to do it Lambda.World (Typeform). Non invasive and with responsive design.
Thanks!
=> Changes in the website to modify Lambda.World Conference and add a C4P for unconference

_layouts/default.html
The RSS feed is not automatically discoverable because the <head> section does not indicate it. And it should, it makes discovery easier - for example Firefox's "Subscribe to this page" button does not work without it.
=> Update head to include the RSS link

posts/2016-09-21-edsls-part-1.md, posts/2016-10-26-edsls-part-2.md
Scheduled for Wednesday October 12.
cc @S11001001
=> New blog post: EDSLs as functions

_events/2017-03-23-summit-nyc.md, _events/2017-06-03-summit-copenhagen.md
I feel better about encouraging people to apply for the CFP/attend the event when things like this are made explicit.
Addresses https://github.com/typelevel/typelevel.github.com/issues/139
=> Add code of conduct section and links to Summit events

_includes/license.html, _layouts/post.html, about.html, blog/feed.rss
I am a user of rss feed aggregators and find the current rss feed not as
useful as it could be. You can checkout the current state by looking at
http://typelevel.org/blog/feed.rss on feedbucket.com. The list of blog posts is
limited to 10 entries and the descriptions are very terse.
The terseness, I think, is a bug with the `{% if post.excerpt %}` line.
At some point Jekyll decided to auto-generate excerpts if one is not
given in the YAML header. So I think this `if` statement is always true.
I greped the posts directory and found no use of the `excerpt` variable
so I made the decision to just remove the use of the variable in the
feed.rss file.
The end result is a useful rss feed. It can be previewed at
feedbucket.com using this link …
=> make rss great again

projects/index.html
The project page is fairly long This would allow deep links like http://typelevel.org/projects/#scala-exercises , for example in README badges.
`slugify: 'raw'` converts to lowercase and replaces spaces, not allowed in HTML IDs, with dashes.
=> add fragment IDs for each project to support deep links

_data/incubator.yml
Mouse was recently moved to Typelevel.
This change update the github URL on the site.
=> Change Mouse github URL to repo under Typelevel

_events/2018-05-18-summit-berlin.md
=> Add Signify as a silver sponsor of Berlin 2018

_data/authors.yml, posts/2018-05-09-product-with-serializable.md
This is a document that I've had sitting on my laptop for a while. I
figured that I might as well put it in a public place, and the typelevel
blog is the first place that came to mind.
I now see that Noel Welsh has published something similar [here](https://underscore.io/blog/posts/2015/06/04/more-on-sealed.html).
This goes into a bit more detail with type LUBs, which may be helpful to
someone?
=> Add Product with Serializable blog post

_projects/cats.md
At this point Cats is pretty stable and is used widely in production and
across other libraries. I think that we can remove the "experimental"
tag.
=> Remove "experimental" from Cats description

_events/2018-03-20-summit-boston.md, _events/2018-05-18-summit-berlin.md, index.html
These events are over, so they should no longer be featured on the home page.
=> Remove historical events from the home page

_projects/circe.md
I don't really see any value in having circe listed as a Typelevel project. The removal here doesn't change anything about the way circe is maintained, or anything at all, really, apart from the fact that "circe is a Typelevel project" will no longer be true.
r? @larsrh @milessabin @non
=> Remove circe from Typelevel projects

_events/2019-04-01-summit-philadelphia.md
I think it's better to point to the NEScala web site, now that it's up. The info on the site is more detailed than the info on the Twitter post.
=> Change NEScala link from Twitter post to https://nescala.io

about.html
@larsrh caught this on #257 and I overlooked it until after I'd hit merge.
=> Link to Scala CoC instead of Typelevel CoC from /about.html

_includes/code-of-conduct-header.html, _includes/code-of-conduct.html
I can dig up relevant ticket links if demanded, but this gets us back to [0f8d4703](https://github.com/scala/scala-lang/blob/0f8d470312b42134fc993592c704fb0c32253dd4/conduct.md), with our deltas for venues and moderators.
Thanks to @SethTisue for the gentle reminders, and all who improved things upstream.
=> Synchronize Scala Code of Conduct with upstream

Dockerfile
* openjdk-8-jdk isn't available on buster
* sbt-1.0.4 fails to install now, but sbt-1.3.0 works
=> Bump Docker dependencies

posts/2019-11-13-Update-about-sustainability-program.md
No author appeared on that post because it's missing the standard metadata.
=> Add frontmatter to November update

_posts/2020-10-30-concurrency-in-ce3.md
renamed joinAndEmbedNever to joinWithNever as per https://github.com/typelevel/cats-effect/issues/1500
did not check the correctness of any other examples
=> renamed joinAndEmbedNever to joinWithNever in 2020-10-30 blog post

.github/workflows/cache.yml, .github/workflows/ci.yml, README.md
I created a [Typelevel cachix](https://app.cachix.org/cache/typelevel#pull) instance.  This will cache the dev shell for MacOS and Linux, and use the cachix to potentially speed up the CI.
=> Push to Typelevel cachix instance

steering.md
It would be better to synchronize this list from governance (#326), but this indirection keeps it accurate in the meantime.
=> Point to the official steering committee listing

_includes/_section-projects.html
We can quibble about which these are, but this matches the status quo.
See #347.
=> Restore "core" projects to front page

README.md, _posts/2022-07-25-welcoming-new-steering-committee-members.md
Slightly changed closing paragraph and and opening paragraph from steering committee's shared draft -- added a reference to the previous post in the opening paragraph.
I'll be out of town this upcoming week, so if any changes need to be pushed, @rossabaker or others are welcome to do so! I should still have access to comment on this PR and press buttons via my phone, though. I set the date to this coming Monday for now -- open to that change as well.
FYI: I can't get the site to build via the first recommended method in the README, so I haven't been able to preview these changes other than via my Markdown viewer. Unfortunately I don't have time to look too deep into it yet...
gist in case it may be worth a separate bug report, or otherwise I may have missed a build step: …
=> Fix README typo and add 2022-07 new members post

_data/about.yml, _data/cta.yml, _data/description.yml, _data/nav-scala.yml, _includes/_cta-steering.html, _includes/_section-about.html, about/index.html, steering-committee.md
I realized we don't have any official link to steering committee information, other than our more date-dependent blog posts. Here's my attempt at resolving that.
Modules from "About" page are removed. I think they take up a lot of space, and one could click on the About link to see them all. I also referenced the Code of Conduct and Steering Committee.
I added a simple white CTA for Steering Committee below the red CTA for Code of Conduct. It's very simply done, reusing some other CSS classes since I'm not a frontend expert... There is no other place in the current layout that has two CTAs next to each other, so I had to figure something out.
add /steering-committee
I added a clause about org-level announcements, since we do that here in addition to technical posts.
=> Copy updates, add steering committee cta to about page

_config.yml
This is what the links on the RSS feed look like now:
```
<link>/typelevel.github.com</link>
<link>/typelevel.github.com/blog/2022/09/19/typelevel-native.html</link>
<link>/typelevel.github.com/blog/2022/09/12/tuple-announcement.html</link>
<link>/typelevel.github.com/blog/2022/09/06/new-website-layout.html</link>
<link>/typelevel.github.com/blog/2022/07/25/welcoming-new-steering-committee-members.html</link>
<link>/typelevel.github.com/blog/2022/04/01/call-for-steering-committee-members.html</link>
<link>/typelevel.github.com/blog/2022/01/19/governing-documents.html</link>
<link>/typelevel.github.com/blog/2021/11/15/on-recent-events.html</link>
<link>/typelevel.github.com/blog/2021/05/05/discord-migration.html</link>
<link>/typelevel.github.com/blog/2021/04/27/community-safety.html</link> …
```
=> Update site baseUrl to fix RSS feed permalinks

_config.yml
Reverts typelevel/typelevel.github.com#400
Breaks the site. Let's roll this back while we fix.
=> Revert "Update site baseUrl to fix RSS feed permalinks"

_includes/_head.html
We used to do this as in 736cd9228716dc37aeff4e3bb535041e0970f0f8, but that script 404s and the config doesn't work anymore.  This is the same idea.  
Fixes #391.
=> Bring back mathjax

_data/nav-social.yml, _data/nav.yml, _includes/_footer.html
Specifically, our new official home at Fosstodon. This also serves as a verification link for Fosstodon, and the `rel="me"` is required, which is why it's being handled out-of-band from the other links; if we're comfortable always using `rel="me"` for social links, we could unify this.  (Opinions welcome.)
Fixes #403.
=> Add a social pointer to Mastodon

collections/_projects/fs2-data.md
Add fs2-data to the projects page.
Preview of the generated card:
@satabin Are you ok with this description?
Part of https://github.com/typelevel/governance/issues/69
=> Add fs2-data to projects page

.gitignore, _data/filter-projects.yml, _includes/_project_membership.html, _includes/_tab-projects.html, projects/affiliate.html, projects/index.html, projects/member.html, projects/organization.html
Add `/projects/organization` and `/projects/affiliate` pages along with tab selectors.
All Projects:
Organization Projects:
Afilliate Projects:
=> Add filter tabs to Projects page

_includes/_section-blog.html, _layouts/post.html, blog/governance.html, blog/index.html, blog/social.html, blog/summits.html, blog/technical.html
We don't currently have any images for our blog posts, so everything uses the placeholder image, which I don't think adds value.
Before:
After:
Previous discussion: https://github.com/typelevel/typelevel.github.com/issues/348
Tagged a handful of folks who have worked on the site in the past, but I'm happy to hear thoughts from everyone :).
=> Remove placeholder images from blog posts

_includes/_head.html, _includes/_js-bottom.html, _includes/_masthead.html, _includes/_section-blog.html, _includes/_section-projects.html, _sass/components/_about.scss, about/index.html
Removes the "animate on scroll" animation of the hexagons on the About page.
I don't have a preview for this... because it's hard. Just trust me, there's no animation.
This is clearly a personal preference thing, but I would like to ditch all animation across the whole site.
Update: This PR now removes all animation effects from the site.
=> Remove animation on all pages

_data/projects.yml
cats-time lives here now: https://github.com/typelevel/cats-time
=> Update cats-time github repo link

_data/projects.yml
=> Update fs2 repo link

_data/projects.yml
Update:
- https://github.com/typelevel/kind-projector
- https://github.com/typelevel/kittens
- https://github.com/optics-dev/Monocle (including description)
- https://github.com/typelevel/scalacheck
- https://github.com/typelevel/simulacrum
- https://github.com/typelevel/spire
- https://github.com/typelevel/squants
Removing "affiliate" status where projects are now hosted by typelevel
=> Updates to projects.yml

_includes/_cta-projects.html
The current link is bypassing the template. This more generic link takes you to the issue-template-picker and is unlikely to go stale.
=> Fix project submission link

_data/authors.yml, collections/_posts/2023-04-03-typelevel_toolkit.md
First full blogpost I've written, so please any feedback and nitpick welcome!
=> Add typelevel toolkit blog post

_includes/_section-projects.html
This restores the core project listing on the homepage which unfortunately broke back in https://github.com/typelevel/typelevel.github.com/pull/418
=> Fix "core projects" listing on homepage

README.md, _data/description.yml, _data/filter-platforms.yml, _data/nav.yml, _data/projects.yml, _includes/_project_platforms_tag.html, _includes/_section-projects.html, _includes/_tab-platforms.html, platforms/index.html, platforms/js.html, platforms/jvm.html, platforms/native.html, projects/affiliate.html, projects/index.html, projects/organization.html
**TLDR:**
- replaces `category` tag with `platform` tag
- page for each platform we support (JS, JVM, Native)
While open, this PR is available for preview here:
https://valencik.github.io/typelevel.github.com/platforms/
(note however that some links will be broken there)
I recommend checkout out that preview because these screenshots are probably already out of data (they are).
I would like for these pages to:
- talk a bit about the support and capabilities on each platform
- e.g. the native page should link to [Arman's blog post](https://typelevel.org/blog/2022/09/19/typelevel-native.html)
- e.g. the js page should briefly discuss the JS environment options: browser, severless, cli
-  list the projects that are supported by each platform
I want to be slightly more than just another …
=> Add Platforms Tags and Page

_data/filter-platforms.yml, platforms/index.html
Currently the project listing is the same as that of the native platform page, but that might not be the case for long.
=> Add projects support all platforms to platform index page

_includes/_project_card.html, _includes/_project_membership.html, _includes/_project_platforms_tag.html, _includes/_section-projects.html, platforms/index.html, platforms/js.html, platforms/jvm.html, platforms/native.html, projects/affiliate.html, projects/index.html, projects/organization.html
Builds on https://github.com/typelevel/typelevel.github.com/pull/445
No user facing changes.
Reduces some duplication by having a single project card include and leveraging that everywhere.
Additionally, reduces some indirection and inlines the project membership and platforms in that project card include.
=> Add project card include

_config.yml, _includes/_js-bottom.html
This fixes syntax highlighting for the site.
Currently Scala code looks like this (https://typelevel.org/blog/2018/11/28/http4s-error-handling-mtl-2.html)
This is how it looks after the fix
=> Fix syntax highlighting

_config.yml
After #454, looks like the live site still has the default jekyll syntax highlighter enabled, conflicting with highlight.js. (Inspecting element on any piece of code on the site will show both `highlighter-rouge` and `hljs...`)
This is due to github-pages using a different version of jekyll (3.9.3) than the one defined in Gemfile. This fix actually fixes that for the live site.
See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#syntax-highlighting.
=> Fix syntax highlighting for github pages (cont)

_data/projects.yml
The `github` link is supposed to be the link to the repo.
`permalink` can link to the project page / documentation.
=> Specify github repo url for calico

collections/_events/2023-10-26-summit-nescala.md
Adds an events page for the Typelevel Summit 2023
=> Add Typelevel Summit 2023 event

collections/_events/2023-10-26-summit-nescala.md
The content is currently pointing to an illegal version of the URL.  Maybe the publication problem is that the Markdown generator is silently checking URLs, and this is getting a 404?  Let's try changing to a known-good that doesn't involve any redirection, and see if that fixes it.
=> Fix NE Scala URL

_data/projects.yml
Adding cats-stm as an affiliate project as per https://github.com/typelevel/governance/issues/119
cc. @TimWSpence
=> Add cats-stm to projects

_data/projects.yml
Adding ldbc as an affiliate project as per https://github.com/typelevel/governance/issues/123
@valencik
Thanks!
Additional support was provided in reference to pull requests for other projects.
The order is probably ABC... order, so I described them as such.
Please let me know if I missed anything!
=> Add ldbc to projects

_config.yml
The mission statement taken from:
https://typelevel.org/blog/2022/04/01/call-for-steering-committee-members.html
=> Update site description with mission statement

_data/gsoc-ideas.yml, _includes/_gsoc_idea_card.html, gsoc/ideas.html
Still want to add some ideas and tweak existing ones but the current iteration of this page is overdue for an update.
=> Expand GSoC ideas page

_data/projects.yml
Looks like the Projects page is missing a link to Literally.
=> Add "literally" to the projects page

collections/_posts/2024-02-24-github-seats.md
Adds a small post detailing the removal of 25 maintainers.
Users were identified by checking each member of the Typelevel org from https://github.com/orgs/typelevel/people
And looking to see if they had any commit, issue, or PR activity since 2023-01-01 with a GH search like the following:
https://github.com/search?q=author%3Avalencik+org%3Atypelevel+author-date%3A%3E2023-01-01&type=commits&s=author-date&o=asc
**DO NOT MERGE**
The removal has not actually happened yet, we've just identified the users.
Hoping to do the removal tomorrow.
Please review the content here anyways though.
:)
**DO NOT MERGE**
=> Add blog post on GH seat limit

_data/projects.yml
Some of this was originally done in https://github.com/typelevel/typelevel.github.com/pull/424
But I think I messed things up in the big one file squish.
Oh well, I've gone through all the affiliate projects now and I think this is it.
=> Remove `affiliate` from a few org projects

collections/_posts/2021-05-05-discord-migration.md
The discord announcement blog post has a discord invite link in it. It was reported in `#admin` (back at the start of April, sorry for the delay!) that someone had tried to use this link and it's apparently expired. Since it sounds like people still try to join the discord via this link, I'm updating it :)
=> update discord link

_data/projects.yml, _includes/_section-projects.html, _sass/components/_projects.scss
@valencik nerd-sniped me, this PR it's the outcome.
If we want to change the listed projects it's enough to pick different ones in the `names` array
```
{% assign names = "Cats|Cats-Effect|fs2|http4s" | split: "|" %}
```
The values must correspond to titles in the [projects data](https://github.com/typelevel/typelevel.github.com/blob/main/_data/projects.yml)
I'll say that either four or six projects is the perfect number to show on the home
=> Change the projects listed on the homepage

_includes/_head.html, _includes/_js-bottom.html
Implements a few suggestions from [webbkoll](https://codeberg.org/dataskydd.net/webbkoll) to improve privacy and security:
- The Content-Security-Policy restricts where various kinds of subresources may be sourced from.  Think of it as an allowlist.  This is more useful if we were rendering content that wasn't reviewed in advance (e.g., comments), but it makes clear who we trust, and gave us a chance to consolidate that in the case of MathJax.
- Adds hashes to our stylesheets and CSS.  The browser will refuse to load them if the contents change.  Which, since they're versioned, is probably real bad if they do.
- The referer policy instructs browsers not to leak trackable information when following links off our site.
=> Privacy improvements

_data/gsoc-ideas.yml, _data/gsoc-projects.yml, _includes/_gsoc_project_card.html, gsoc/index.html, gsoc/past-projects.html
(Begins) refreshing our materials for GSoC 2025.
1. Status update on landing page i.e. org application in-process.
2. Clear out completed projects from Ideas. (🎉 so many to remove!! 😮 )
3. Add last years' projects to Past Projects. (I only added the "official" GSoC projects, 🤷, esp. since Google itself may be looking at these pages to evaluate our application)
=> GSoC 2025 refresh

_data/cta.yml, _data/filter-about.yml, _includes/_tab-about.html, about/contribute.html, about/contributing.html, about/index.html
This PR adds a section to the About page about how to contribute to Typelevel, with a main focus on financial contributions.
Special shout out to @samspills who had already written most of this contributing content previously. :heart: 
Closes https://github.com/typelevel/typelevel.github.com/issues/415
=> Add Contributing page, revamp About page

_data/projects.yml
Hi!
[ldbc](https://github.com/takapi327/ldbc?tab=readme-ov-file#modules-availability) now supports Scala.js and Scala Native.
Therefore, we have updated the contents of this repository.
Thanks!
=> Added Scala.js and Scala Native support to ldbc.

.github/CODEOWNERS
This should perhaps be a more specific team than steering, but I think this works for now.
I think it would be ok if it was one review from anyone on steering or the CoC committee.
But we currently lack a GH team for the CoC committee.
=> Add CODEOWNERS for event posts
