_posts/2015-07-13-type-members-parameters.md, _posts/2015-07-16-method-equiv.md
Second in a series on type parameters and members, for posting on July 16.
NB: Links to the previous post will not work on GH, because they use `post_url`, which only works on the site.
=> New post: "When are two methods alike?"

_posts/2015-07-13-type-members-parameters.md, _posts/2015-07-16-method-equiv.md, _posts/2015-07-19-forget-refinement-aux.md
Third in a series on type parameters and members, for posting on July 20.  Preceded by #44.
NB: Links to the previous post will not work on GH, because they use post_url, which only works on the site.
=> New post: "What happens when I forget a refinement?"

_posts/2015-07-16-method-equiv.md, _posts/2015-07-23-type-projection.md, _posts/2015-07-27-nested-existentials.md
Fifth in a series on type parameters and members, for posting on July 27. Preceded by #46.
NB: Links to the previous post will not work on GH, because they use `post_url`, which only works on the site.
=> New post: "Nested existentials"

_posts/2015-08-06-machinist.md
Original author: @non 
Source: https://gist.github.com/non/a6ff3c0796e566db20d1
=> New post: Machinist vs. value classes

_posts/2015-08-07-symbolic-operators.md
Original author: @non
Source: https://gist.github.com/non/3abdb35a72c39276d3d9
=> New post: Symbolic operators and type classes for Cats

blog/archive.md, blog/index.html
=> Blog archive page

_events/2016-03-summit-philadelphia.md
=> list of topics for the CfP on the event page

index.html
=> More speakers, less papers

_data/incubator.yml
I think I like the name with a capital letter. Sorry for not mentioning it earlier :-)
=> Update Monix entry in incubator.yml

_events/2016-03-summit-philadelphia.md
=> remove old information from Philadelphia Summit page

_posts/2016-01-28-existential-inside.md, _posts/2016-05-10-internal-state.md
This is the ninth post in the TP&TM series.
=> New post: "Making internal state functional"

_layouts/default.html
... instead of the Philadelphia summit
=> Link to the /events page in the footer

_events/2016-09-30-conf-cadiz.md
First talk sent from a good friend :-).
Please, can you review it @larsrh? 
Thanks!
=> Add @dialelo talk to proposals

_posts/2016-09-19-variance-phantom.md
Even more variance and phantom parameter stuff than you can shake a stick at.
For publication Monday, September 19.
=> New post: "Choosing variance for a phantom type"

_posts/2016-09-21-edsls-part-1.md
Pretty complete draft I think, but a draft nonetheless. Please give feedback :-)
=> [RFC] New blog post: It's programs all the way down

_posts/2016-09-30-subtype-typeclasses.md
=> New blog post: Subtype type classes don't work

_layouts/page.html, _layouts/post.html, events/index.html
Closes #86.
Paging @adelbertc.
I know very little about these things, so I'll let others judge whether or not this is an improvement.
=> increase content width on some pages

_data/authors.yml, posts/2016-11-17-heaps.md
Republished from chrisokasaki/scads@e78233ac6a787b7c66b44cd6139392418b214eb9 with the explicit permission of @chrisokasaki.
Changes to the original post:
- minor editing
- `tut`ification
=> new post: API Design for Heaps (aka Priority Queues)

_data/incubator.yml
Following directions in https://github.com/typelevel/general/issues/48
=> TwoTails to Incurbator Status

_data/authors.yml, posts/2016-12-17-scala-coc.md
=> new post: endorsing the new Scala CoC

_data/authors.yml, _events/2017-03-23-summit-nyc.md
~~Do not merge yet. 3 speakers pending confirmation.~~
=> NYC: accepted talks

posts/2017-02-13-more-types-than-classes.md
For posting on Monday, Feb 13.
=> New post: 'There are more types than classes'

.travis.yml, build.sbt, posts/2017-02-13-more-types-than-classes.md
As suggested in #143 by @larsrh.  I've only guarded the blocks that would output something close enough to the original manual blocks, and also have all dependency blocks evaluated.
/cc @tpolecat
=> Tutify "There are more types than classes"

build.sbt, posts/2017-03-01-four-ways-to-escape-a-cake.md
For publication on March 1.
(There is a [tut patch](https://github.com/S11001001/typelevel.github.com/compare/four-ways-to-escape-a-cake...S11001001:four-ways-to-escape-a-cake+tut) to this, similar in spirit to #145; lacking output, it is more difficult to review.)
=> New post: "Four ways to escape a cake"

posts/2017-03-01-four-ways-to-escape-a-cake.md
Re #146, similar in spirit to #145.
=> tutify "Four ways to escape a cake"

posts/2016-10-26-edsls-part-2.md
Apparently being at a conference gives me motivation/time to work through my PR backlog :-) Apologies for the late fix
=> EDSLs part 2 blog post: fix comment link

_data/authors.yml, posts/2017-04-02-equivalence-vs-equality.md
This has been edited until the point where the `hasheq` library is needed. I still need to contemplate whether to include some toy version of the actual code so that we can run it through tut, or to leave it as it is and link to the repository.
=> guest post by Tomas Mikula: "Equivalence versus Equality"

_data/incubator.yml
Libra has been [accepted as an incubator project](https://github.com/typelevel/general/issues/64)
=> Add Libra to incubators list

_data/incubator.yml
=> Add melrief/sonic to incubator.yml

_includes/conduct.html
Now sure why link with www is redirecting wrong
=> Fix Haskell Now link

_projects/ensime.md
These past few days I've been thinking a lot about why ENSIME is a member of Typelevel. My soul searching has led me to conclude that I don't feel that ENSIME is a good fit for a formal relationship with Typelevel and I've been sitting on this post over the weekend.
I'd like to say that this has been a very difficult decision to reach and I fear for any fallout. Therefore I request that this is not publicised (at least not loudly).
I have discussed this with other long term contributors and we feel that we have always been the "oddball project" who are out of place in the Typelevel line-up, so it is perhaps for the best. We're all still committed to fostering an inclusive environment.
I truly hope that this does not affect my personal friendship with anybody in Typelevel - especially …
=> remove ensime from the project list.

posts/2017-06-13-libra.md
I tried to follow the code examples, and got tripped up on some things.
Hopefully, the following changes are useful to others, as well.
This is a really great article.  Thank you!  I'm looking forward to learning more about Libra.
=> Fix bugs in Libra post

posts/2017-06-13-libra.md
Adds tut to the post.
The later code snippets require typelevel scala, so can't be tutified easily.
=> Tutify Libra post

_data/authors.yml, posts/2017-06-21-ciris.md
Add follow-up blog post to the talk at the Copenhagen Summit.
=> Add Ciris blog post

_data/incubator.yml
Follow-up to https://github.com/typelevel/general/issues/77.
=> Add Ciris to list of incubator projects

_data/authors.yml, posts/2017-08-04-cats-1.0-mf.md
=> post: cats 1.0.0-MF announcement

_data/incubator.yml
Rather-belatedly making the change for https://github.com/typelevel/general/issues/80!
=> Add decline to incubator.yaml

_events/2017-10-26-conf-cadiz.md
Add the Typelevel Unconference that is going to be co-located with LW.
Could you check it @larsrh, thank so much!!
=> Adds the Typelevel Unconference - Lambda World [2017]

_data/authors.yml, posts/2017-12-27-optimizing-final-tagless.md
My first typelevel blog post 🎉
I didn't reread yet, but would love to hear some early feedback :)
=> Add new blog post - Optimizing Tagless Final Programs

posts/2015-07-23-type-projection.md, posts/2017-12-20-who-implements-typeclass.md
=> Corrections for a couple blog posts

posts/2018-04-13-rethinking-monaderror.md
A new blog post about MonadError and its usability. Would love to hear some feedback or proofreading
:)
=> Rethinking MonadError - new blog post

posts/2018-04-13-rethinking-monaderror.md
Fixes kind of second MonadBlunder encoding
=> More blog post corrections

posts/2018-06-07-shared-state-in-fp.md
First shared in this [gist](https://gist.github.com/gvolpe/d4facceedf12ab7870934cbf9d6174e9) but here I added a few other things after getting some feedback from Reddit :)
Also thanks to @tpolecat for pushing me to write it as a `Typelevel` blog post.
=> Blog post: Shared State in Functional Programming

_projects/cats.md
Since Alleycats was moved into Cats repository.
=> Update Alleycats link

css/main.scss
=> increase contrast of black-on-white

_data/authors.yml, _layouts/post.html, _scss/_reset.scss, css/main.scss, posts/2018-08-06-Refactoring-Monads.md, posts/2018-08-07-refactoring-monads.md
I wrote up this short blog post to explain to my coworkers some refactoring I'd done. I mentioned it in passing to @larsrh, who glanced it over and suggested it might be worth reviewing for a wider audience. The whole thing is rather trivial and intended more for beginners than anything.
If Typelevel is interested, I'm happy to contribute it. If not, my feelings won't be hurt, I'll share it with my coworkers as I had originally intended.
If we decide to publish it here, there're a few formatting issues that I'd appreciate a bit of help with. The biggest one is a markdown table that seems to render badly on the Typelevel site but looks fine in plain markdown. I think the default github CSS is fine, but the Typelevel site is perhaps missing some configuration. I was a little nervous to …
=> add blog post: refactoring with monads

posts/2018-08-25-http4s-error-handling-mtl.md
Please have a look @oleg-py !
~I used `tut` for everything except for the last part because the dependency `meow-mtl` could not be resolved. If anybody has any idea of how to solve it (maybe adding a Resolver for tut?) I'd be glad to fix it.~ 
Feedback from @rossabaker would be greatly appreciated :)
=> Blog post: Http4s error handling using Cats Meow MTL

posts/2018-08-25-http4s-error-handling-mtl.md
- Removing syntax: I realized it was no longer necessary since now the function is only called once at the routes level whereas before it was called multiple times per response (hence it made sense having syntax).
- Relaxing constraint of `RoutesHttpErrorHandler.apply` to `ApplicativeError`.
=> [Corrections] - Error handling MTL blog post

posts/2018-09-04-chain-replacing-the-list-monoid.md, posts/2018-09-04-do-not-use-list-monoid.md
We can only merge this when `Cats` 1.3.0 is released, I'll also need to do some proofreading.
=> Add Chain Blog post

posts/2017-12-27-optimizing-final-tagless.md
=> Optimize final tagless review

posts/2016-10-17-minicheck.md, posts/2016-11-17-heaps.md, posts/2017-02-13-more-types-than-classes.md, posts/2017-05-02-io-monad-for-cats.md, posts/2018-04-13-rethinking-monaderror.md, posts/2018-05-09-product-with-serializable.md, posts/2018-08-07-refactoring-monads.md, src/main/scala/FrontMatter.scala
~I'm also trying to get compiler plugins to work.~
=> tut improvements

posts/2018-09-29-monad-transformer-variance.md, src/main/scala/FrontMatter.scala
Every once in a while [people](https://github.com/typelevel/cats/issues/556) [ask](https://github.com/typelevel/cats/issues/2310) [about](https://github.com/typelevel/cats/issues/2538) this.
I thought that it would be nice to provide a more detailed answer in a
single place so we can link to it from the Cats FAQ.
Note: I had to add the `-Ypartial-unification` flag for one of the code
samples to compile. It's quite possible that I should be doing this a
different way than I did.
=> Add a blog post about variance and monad transformers

posts/2018-08-25-http4s-error-handling-mtl.md
=> Updating [meow-mtl] blog post to compile using kind projector

posts/2018-10-06-intro-to-mtl.md
Feedback appreciated, thanks a lot to @larsrh who made kind-projector and partial unification work 🎉
=> New MTL blog post

posts/2018-11-02-semirings.md
Follow up to the semiring post
=> Add another item to the addendum

posts/2018-11-28-http4s-error-handling-mtl-2.md
I've got some feedback from John and after having a chat I'm updating the blog post accordingly.
We still have a pending discussion on "polymorphic code" but I think the only thing mentioned about it in this update is correct, however I would appreciate your review @jdegoes , thanks!
=> Updating "error handling" blog post 

_layouts/default.html
=> added a banner to promote  fundraising campaign

blog/index.html
Add link back to repository in sidebar
=> Add GitHub repo link

project/build.properties
Bumping sbt version
~(but also just trying to get the CI to rebuild)~
Admittedly, this PR was originally created just to get CI to run again on https://github.com/typelevel/typelevel.github.com/pull/276
=> Bump sbt to 1.3.9

_data/incubator.yml
Approved in: https://github.com/typelevel/general/issues/97
=> Adding cron4s after approval for Incubator

posts/2020-06-10-confronting-racism.md
This blog post is not technical in nature, and I tried to be very careful to use facts and figures, to rely on other authorities, make reasonable/constructive suggestions, and tie my ideas back to Typelevel and the technology industry in general. I did this work as part of time away from my work for the  https://www.shutdownstem.com/ strike on June 10th of this year.
It is unfortunately rather U.S.-centric, and I understand that Typelevel is larger than the United States.
I hope you will consider including it. Many professional organizations, even those which have been less overtly political than Typelevel in the past, have published statements explicitly condemning racism and supporting Black Lives Matter. I do not think I can (or should) speak for Typelevel, but I do feel like some …
=> Typelevel blog concerning recent events / dealing with racism in tech

_data/incubator.yml
See https://github.com/typelevel/general/issues/109
=> Add uniform-scala

_data/incubator.yml
=> Add missing double-quote

.github/workflows/ci.yml, README.md, flake.lock, flake.nix, gemset.nix
Bundler still doesn't work for me, and the Docker container is gone.  This works well for me:
* README.md documents it
* flake.nix drives it
* gemset.nix and flake.lock are generated.  Sorry.
Adds a CI workflow that verifies that the site builds.  Depends on Nix, but I don't care to faff about with Ruby-in-YAML.
Fixes #310.  Mitigates #251.
=> Add a devshell and CI

collections/_projects/export-hook.md, collections/_projects/imp.md, collections/_projects/kind-projector.md, collections/_projects/local-implicits.md, collections/_projects/machinist.md, collections/_projects/macro-compat.md, collections/_projects/simulacrum.md
Some of these are past their expiration dates, but restoring parity with the old site for now.
Fixes #352
=> Restore macro projects

collections/_projects/argonaut-shapeless.md, collections/_projects/cats-collections.md, collections/_projects/cats-effect.md, collections/_projects/cats-mtl.md, collections/_projects/cats-tagless.md, collections/_projects/cats-time.md, collections/_projects/kittens.md, collections/_projects/mouse.md, collections/_projects/scalacheck-shapeless.md, collections/_projects/shapeless-contrib.md
=> Add "companions and extensions" from old site

_data/description.yml, _data/nav.yml, _includes/schedule.html, _includes/sponsors.html, _includes/venue_map.html, _layouts/event.html, _sass/components/_events.scss, collections/_events/2016-03-02-summit-philadelphia.md, collections/_events/2016-05-04-summit-oslo.md, collections/_events/2016-06-11-hackday.md, collections/_events/2016-07-16-hackday.md, collections/_events/2016-08-13-hackday.md, collections/_events/2016-09-14-lake-district-workshop.md, collections/_events/2016-09-17-hackday.md, collections/_events/2016-09-30-conf-cadiz.md, collections/_events/2016-10-15-hackday.md, collections/_events/2016-10-27-scala-io.md, collections/_events/2016-11-12-hackday.md, collections/_events/2016-12-10-scalaxhack.md, collections/_events/2017-01-21-hackday.md, collections/_events/2017-03-23-summit-nyc.md, collections/_events/2017-06-03-summit-copenhagen.md, collections/_events/2017-10-26-conf-cadiz.md, collections/_events/2018-03-20-summit-boston.md, collections/_events/2018-05-18-summit-berlin.md, collections/_events/2019-04-01-summit-philadelphia.md, collections/_events/2019-06-14-summit-lausanne.md, collections/_events/2020-03-12-summit-nyc.md, css/main.scss, events/index.html
The event pages still looks ~~like garbage~~ imperfect, but this restores important history.
See #345.
=> Restore events

index.md
=> Set title for home page

collections/_projects/export-hook.md, collections/_projects/index.md, collections/_projects/libisabelle.md, collections/_projects/local-implicits.md, collections/_projects/machinist.md, collections/_projects/macro-compat.md, collections/_projects/scala.md, collections/_projects/shapeless-contrib.md, collections/_projects/structures.md, collections/_projects/unique.md
Not doing anything with it yet, but we can filter on this later.
=> Mark archived projects in metadata

_includes/_section-about.html
=> Unlimited abouts

_includes/_section-projects.html, _sass/components/_projects.scss, projects/index.html
Uses shields.io in Typelevel colors.  I don't know that I love the look of it, but it's a starting point.  Discuss.
Fixes #357.
=> Distinguish member and affiliate projects

_config.yml
=> Typelevel.scala -> Typelevel

_includes/_cta-projects.html
A better version requires https://github.com/typelevel/governance/issues/57
=> Fix the project submission button

Gemfile, Gemfile.lock, gemset.nix
I think this will fix the problem @JasnaMRB ran into trying to run the site using bundler directly (#378).  Jasna is on Ruby 3, and I am on Ruby 2.  I don't know what I'm doing, but I think Jasna's problem is https://github.com/jekyll/jekyll/issues/8523.
=> Add webrick for Ruby 3

_includes/code-of-conduct.html
This isn't DRY with https://github.com/typelevel/.github/pull/7
=> Remove @rossabaker as moderator

collections/_projects/scala.md
=> remove Typelevel Scala from projects list

collections/_posts/2022-09-06-new-website-layout.md
When I renamed the file to be Sept 6, not Sept 4... 🤦🏽‍♀️
=> Add Sept 6 blog post from #394, got dropped

collections/_projects/export-hook.md, collections/_projects/libisabelle.md, collections/_projects/local-implicits.md, collections/_projects/machinist.md, collections/_projects/macro-compat.md, collections/_projects/shapeless-contrib.md, collections/_projects/structures.md, collections/_projects/unique.md
=> remove all archived repos

_includes/_head.html, blog/feed.rss
I tested locally, discovery and loading the RSS file in a client works.
File copy/pasted from the old website design. My website's own RSS file does more work and sanitization than this, but this is fine for now.
=> Fix #392: Add blog/feed.rss

collections/_projects/parsley-cats.md
https://github.com/typelevel/governance/issues/70
=> Add parsley-cats

_data/projects.yml
Algebra is a part of cats as of https://github.com/typelevel/cats/pull/3918
=> Remove algebra

_data/projects.yml
As per https://github.com/typelevel/governance/issues/78
=> Add Calico and fs2-dom projects

_data/projects.yml
https://github.com/typelevel/governance/issues/86
=> Add Lepus as affiliate project

_data/projects.yml
https://github.com/typelevel/governance/issues/87
=> Add edomata to affiliate projects

_data/projects.yml
Main task in https://github.com/typelevel/governance/issues/92
=> Add endless4s entry in projects.yml

_includes/_code-of-conduct.html
At time of writing, you can preview it here: https://valencik.github.io/typelevel.github.com/code-of-conduct
=> Update Code of Conduct moderators

_data/projects.yml, platforms/index.html, platforms/js.html, platforms/jvm.html, platforms/native.html
- https://github.com/typelevel/governance/issues/104
=> Add ff4s + feral, update platforms blurbs

_data/projects.yml
Hi, I'd like to add `fs2-aes` to project list 🙂 
Migration task: typelevel/governance#109
Submission task: typelevel/governance/issues/107
=> Add fs2-aes to projects

collections/_events/2023-10-26-summit-nescala.md
Examining this vs the last NYC one, this is the only thing I see that looks different.
=> Add sponsors_section

_data/projects.yml
=> Add Grackle

_data/projects.yml
As per https://github.com/typelevel/governance/issues/124
=> Add upperbound as affiliate project

_data/filter-gsoc.yml, _data/gsoc-ideas.yml, _data/gsoc-projects.yml, _includes/_cta-gsoc.html, _includes/_gsoc_idea_card.html, _includes/_gsoc_project_card.html, _includes/_tab-gsoc.html, _sass/components/_gsoc.scss, css/main.scss, gsoc/ideas.html, gsoc/index.html, gsoc/past-projects.html
This PR sets up a scaffold for our GSoC pages that we can then iterate on.
This definitely isn't the final form, just something to get things started.
=> Add initial GSoC pages

_data/projects.yml
As per https://github.com/typelevel/governance/issues/143
=> Add circe as affiliate project

collections/_posts/2024-08-24-call-for-code-of-conduct-committee-members.md
Adds a blog post announcing our new call for Code of Conduct Committee members.
=> Add call for CoC committee members

_data/authors.yml, collections/_posts/2024-12-22-gsoc24-going-feral-on-the-cloud.md
Arman suggested that I create a blog post about my experience in GSoC'24 for the project Going Feral on The Cloud, so here it is!
=> GSoC'24 blog post

_data/authors.yml, collections/_posts/2025-02-21-spotify-foss-fund.md
A short and sweet update about the Spotify FOSS Fund
https://opencollective.com/typelevel/contributions/835051
=> Spotify FOSS Fund post

.github/workflows/ci.yml
Like https://github.com/typelevel/typelevel-nix/pull/213
=> Switch to Lix installer
